//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cmp_Information
    {
        public string Cmp_Name { get; set; }
        public int Cmp_Tel { get; set; }
        public string Cmp_Address { get; set; }
        public byte[] Cmp_Logo { get; set; }
        public string Cmp_TaxID { get; set; }
    }
}
