//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int LocationID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location_Name { get; set; }
        public Nullable<bool> Location_DElete { get; set; }
    
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
