//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore_Web_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Information
    {
        public Emp_Information()
        {
            this.Absence_Table = new HashSet<Absence_Table>();
            this.CheckInDetail = new HashSet<CheckInDetail>();
            this.Emp_Information1 = new HashSet<Emp_Information>();
            this.Salary = new HashSet<Salary>();
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int EmployeeID { get; set; }
        public int Emp_OccupationID { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Tel { get; set; }
        public string Emp_CellPhone { get; set; }
        public string Emp_Address { get; set; }
        public string Emp_E_Mail { get; set; }
        public bool Emp_Gender { get; set; }
        public System.DateTime Emp_StartWorkingDate { get; set; }
        public byte[] Emp_Image { get; set; }
        public Nullable<int> Emp_DeptID { get; set; }
        public Nullable<int> Emp_Report { get; set; }
        public string Emp_Password { get; set; }
        public string Emp_Identity { get; set; }
        public string Emp_Log { get; set; }
        public bool Emp_Dispose { get; set; }
    
        public virtual ICollection<Absence_Table> Absence_Table { get; set; }
        public virtual ICollection<CheckInDetail> CheckInDetail { get; set; }
        public virtual Dept_Information Dept_Information { get; set; }
        public virtual ICollection<Emp_Information> Emp_Information1 { get; set; }
        public virtual Emp_Information Emp_Information2 { get; set; }
        public virtual Emp_Occupation Emp_Occupation { get; set; }
        public virtual ICollection<Salary> Salary { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
